# Colors
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:Tc"

# Split window into panes
unbind %
bind '%' split-window -h -c "#{pane_current_path}"

unbind '"'
bind - split-window -v -c "#{pane_current_path}"

# Refresh configs
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# Resize panes
bind -r j resize-pane -D 3
bind -r k resize-pane -U 3
bind -r l resize-pane -R 4
bind -r h resize-pane -L 4

bind -r m resize-pane -Z

# Change windows
bind -n C-m previous-window
bind -n C-, next-window
bind -n C-t new-window -c "#{pane_current_path}"

# Mouse in tmux
set -g mouse on

# set-window-option -g mode-keys vi

# bind-key -T copy-mode-vi v send -X begin-selection # start selecting text with "v"
# bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle # rectangle selection
# bind-key -T copy-mode-vi y send -X copy-selection-and-cancel # copy text with "y" and return to terminal mode

# unbind -T copy-mode-vi MouseDragEnd1Pane # don't exit copy mode when dragging with mouse

# remove delay for exiting insert mode with ESC in Neovim
set -sg escape-time 10

# tpm plugin manager
set -g @plugin 'tmux-plugins/tpm'

# tmux-sensible
set -g @plugin 'tmux-plugins/tmux-sensible'

# Vim tmux navigator (talk to nvim in navigation)
set -g @plugin 'christoomey/vim-tmux-navigator'

# Catppuccin Flavour
set -g @catppuccin_flavor 'latte' # latte, frappe, macchiato or mocha
set -g @catppuccin_window_status_icon_enable "no"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"
run '~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux'

# Darker selection for semi-transparent terminal
set -g mode-style "bg=#{@thm_overlay_2},fg=#{@thm_crust},bold"

set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right ""

# Session restore
set -g @plugin 'tmux-plugins/tmux-resurrect' # persist tmux sessions after computer restart
set -g @plugin 'tmux-plugins/tmux-continuum' # automatically saves sessions for you every 15 minutes
set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '5'

set-option -g allow-passthrough on
set-option -g status-position top

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
